/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Locations
 * The locations API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateLocationDto,
  LocationDto,
  LocationsControllerFindAllParams,
  UpdateLocationDto
} from '../../models';





export const locationsControllerCreate = (
    createLocationDto: CreateLocationDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LocationDto>> => {


    return axios.default.post(
      `/locations`,
      createLocationDto,options
    );
  }



export const getLocationsControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof locationsControllerCreate>>, TError,{data: CreateLocationDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof locationsControllerCreate>>, TError,{data: CreateLocationDto}, TContext> => {

const mutationKey = ['locationsControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof locationsControllerCreate>>, {data: CreateLocationDto}> = (props) => {
          const {data} = props ?? {};

          return  locationsControllerCreate(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LocationsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof locationsControllerCreate>>>
    export type LocationsControllerCreateMutationBody = CreateLocationDto
    export type LocationsControllerCreateMutationError = AxiosError<unknown>

    export const useLocationsControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof locationsControllerCreate>>, TError,{data: CreateLocationDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof locationsControllerCreate>>,
        TError,
        {data: CreateLocationDto},
        TContext
      > => {
      return useMutation(getLocationsControllerCreateMutationOptions(options), queryClient);
    }
    export const locationsControllerFindAll = (
    params?: LocationsControllerFindAllParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LocationDto[]>> => {


    return axios.default.get(
      `/locations`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getLocationsControllerFindAllQueryKey = (params?: LocationsControllerFindAllParams,) => {
    return [
    `/locations`, ...(params ? [params] : [])
    ] as const;
    }


export const getLocationsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof locationsControllerFindAll>>, TError = AxiosError<unknown>>(params?: LocationsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLocationsControllerFindAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof locationsControllerFindAll>>> = ({ signal }) => locationsControllerFindAll(params, { signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof locationsControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LocationsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof locationsControllerFindAll>>>
export type LocationsControllerFindAllQueryError = AxiosError<unknown>


export function useLocationsControllerFindAll<TData = Awaited<ReturnType<typeof locationsControllerFindAll>>, TError = AxiosError<unknown>>(
 params: undefined |  LocationsControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof locationsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof locationsControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLocationsControllerFindAll<TData = Awaited<ReturnType<typeof locationsControllerFindAll>>, TError = AxiosError<unknown>>(
 params?: LocationsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof locationsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof locationsControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLocationsControllerFindAll<TData = Awaited<ReturnType<typeof locationsControllerFindAll>>, TError = AxiosError<unknown>>(
 params?: LocationsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useLocationsControllerFindAll<TData = Awaited<ReturnType<typeof locationsControllerFindAll>>, TError = AxiosError<unknown>>(
 params?: LocationsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLocationsControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const locationsControllerUpdate = (
    id: string,
    updateLocationDto: UpdateLocationDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LocationDto>> => {


    return axios.default.patch(
      `/locations/${id}`,
      updateLocationDto,options
    );
  }



export const getLocationsControllerUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof locationsControllerUpdate>>, TError,{id: string;data: UpdateLocationDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof locationsControllerUpdate>>, TError,{id: string;data: UpdateLocationDto}, TContext> => {

const mutationKey = ['locationsControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof locationsControllerUpdate>>, {id: string;data: UpdateLocationDto}> = (props) => {
          const {id,data} = props ?? {};

          return  locationsControllerUpdate(id,data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LocationsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof locationsControllerUpdate>>>
    export type LocationsControllerUpdateMutationBody = UpdateLocationDto
    export type LocationsControllerUpdateMutationError = AxiosError<unknown>

    export const useLocationsControllerUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof locationsControllerUpdate>>, TError,{id: string;data: UpdateLocationDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof locationsControllerUpdate>>,
        TError,
        {id: string;data: UpdateLocationDto},
        TContext
      > => {
      return useMutation(getLocationsControllerUpdateMutationOptions(options), queryClient);
    }
    export const locationsControllerRemove = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LocationDto>> => {


    return axios.default.delete(
      `/locations/${id}`,options
    );
  }



export const getLocationsControllerRemoveMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof locationsControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof locationsControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['locationsControllerRemove'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof locationsControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  locationsControllerRemove(id,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LocationsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof locationsControllerRemove>>>

    export type LocationsControllerRemoveMutationError = AxiosError<unknown>

    export const useLocationsControllerRemove = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof locationsControllerRemove>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof locationsControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getLocationsControllerRemoveMutationOptions(options), queryClient);
    }
