/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Locations
 * The locations API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateLocationDto,
  LocationDto,
  LocationsControllerFindAllParams,
  UpdateLocationDto
} from '../../models';





export type locationsControllerCreateResponse201 = {
  data: LocationDto
  status: 201
}

export type locationsControllerCreateResponseSuccess = (locationsControllerCreateResponse201) & {
  headers: Headers;
};
;

export type locationsControllerCreateResponse = (locationsControllerCreateResponseSuccess)

export const getLocationsControllerCreateUrl = () => {




  return `/locations`
}

export const locationsControllerCreate = async (createLocationDto: CreateLocationDto, options?: RequestInit): Promise<locationsControllerCreateResponse> => {

  const res = await fetch(getLocationsControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createLocationDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: locationsControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as locationsControllerCreateResponse
}




export const getLocationsControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof locationsControllerCreate>>, TError,{data: CreateLocationDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof locationsControllerCreate>>, TError,{data: CreateLocationDto}, TContext> => {

const mutationKey = ['locationsControllerCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof locationsControllerCreate>>, {data: CreateLocationDto}> = (props) => {
          const {data} = props ?? {};

          return  locationsControllerCreate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LocationsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof locationsControllerCreate>>>
    export type LocationsControllerCreateMutationBody = CreateLocationDto
    export type LocationsControllerCreateMutationError = unknown

    export const useLocationsControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof locationsControllerCreate>>, TError,{data: CreateLocationDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof locationsControllerCreate>>,
        TError,
        {data: CreateLocationDto},
        TContext
      > => {
      return useMutation(getLocationsControllerCreateMutationOptions(options), queryClient);
    }
    export type locationsControllerFindAllResponse200 = {
  data: LocationDto[]
  status: 200
}

export type locationsControllerFindAllResponseSuccess = (locationsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type locationsControllerFindAllResponse = (locationsControllerFindAllResponseSuccess)

export const getLocationsControllerFindAllUrl = (params?: LocationsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/locations?${stringifiedParams}` : `/locations`
}

export const locationsControllerFindAll = async (params?: LocationsControllerFindAllParams, options?: RequestInit): Promise<locationsControllerFindAllResponse> => {

  const res = await fetch(getLocationsControllerFindAllUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: locationsControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as locationsControllerFindAllResponse
}





export const getLocationsControllerFindAllQueryKey = (params?: LocationsControllerFindAllParams,) => {
    return [
    `/locations`, ...(params ? [params] : [])
    ] as const;
    }


export const getLocationsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof locationsControllerFindAll>>, TError = unknown>(params?: LocationsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerFindAll>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLocationsControllerFindAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof locationsControllerFindAll>>> = ({ signal }) => locationsControllerFindAll(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof locationsControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LocationsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof locationsControllerFindAll>>>
export type LocationsControllerFindAllQueryError = unknown


export function useLocationsControllerFindAll<TData = Awaited<ReturnType<typeof locationsControllerFindAll>>, TError = unknown>(
 params: undefined |  LocationsControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof locationsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof locationsControllerFindAll>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLocationsControllerFindAll<TData = Awaited<ReturnType<typeof locationsControllerFindAll>>, TError = unknown>(
 params?: LocationsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof locationsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof locationsControllerFindAll>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLocationsControllerFindAll<TData = Awaited<ReturnType<typeof locationsControllerFindAll>>, TError = unknown>(
 params?: LocationsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerFindAll>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useLocationsControllerFindAll<TData = Awaited<ReturnType<typeof locationsControllerFindAll>>, TError = unknown>(
 params?: LocationsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerFindAll>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLocationsControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type locationsControllerUpdateResponse200 = {
  data: LocationDto
  status: 200
}

export type locationsControllerUpdateResponseSuccess = (locationsControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type locationsControllerUpdateResponse = (locationsControllerUpdateResponseSuccess)

export const getLocationsControllerUpdateUrl = (id: string,) => {




  return `/locations/${id}`
}

export const locationsControllerUpdate = async (id: string,
    updateLocationDto: UpdateLocationDto, options?: RequestInit): Promise<locationsControllerUpdateResponse> => {

  const res = await fetch(getLocationsControllerUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateLocationDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: locationsControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as locationsControllerUpdateResponse
}




export const getLocationsControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof locationsControllerUpdate>>, TError,{id: string;data: UpdateLocationDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof locationsControllerUpdate>>, TError,{id: string;data: UpdateLocationDto}, TContext> => {

const mutationKey = ['locationsControllerUpdate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof locationsControllerUpdate>>, {id: string;data: UpdateLocationDto}> = (props) => {
          const {id,data} = props ?? {};

          return  locationsControllerUpdate(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LocationsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof locationsControllerUpdate>>>
    export type LocationsControllerUpdateMutationBody = UpdateLocationDto
    export type LocationsControllerUpdateMutationError = unknown

    export const useLocationsControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof locationsControllerUpdate>>, TError,{id: string;data: UpdateLocationDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof locationsControllerUpdate>>,
        TError,
        {id: string;data: UpdateLocationDto},
        TContext
      > => {
      return useMutation(getLocationsControllerUpdateMutationOptions(options), queryClient);
    }
    export type locationsControllerRemoveResponse200 = {
  data: LocationDto
  status: 200
}

export type locationsControllerRemoveResponseSuccess = (locationsControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type locationsControllerRemoveResponse = (locationsControllerRemoveResponseSuccess)

export const getLocationsControllerRemoveUrl = (id: string,) => {




  return `/locations/${id}`
}

export const locationsControllerRemove = async (id: string, options?: RequestInit): Promise<locationsControllerRemoveResponse> => {

  const res = await fetch(getLocationsControllerRemoveUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: locationsControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as locationsControllerRemoveResponse
}




export const getLocationsControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof locationsControllerRemove>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof locationsControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['locationsControllerRemove'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof locationsControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  locationsControllerRemove(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LocationsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof locationsControllerRemove>>>

    export type LocationsControllerRemoveMutationError = unknown

    export const useLocationsControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof locationsControllerRemove>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof locationsControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getLocationsControllerRemoveMutationOptions(options), queryClient);
    }
