/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Locations
 * The locations API description
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const locationsControllerCreateBodyNameMin = 2;
export const locationsControllerCreateBodyNameMax = 60;

export const locationsControllerCreateBodyCoordinatesLonMin = -180;
export const locationsControllerCreateBodyCoordinatesLonMax = 180;

export const locationsControllerCreateBodyCoordinatesLatMin = -90;
export const locationsControllerCreateBodyCoordinatesLatMax = 90;

export const locationsControllerCreateBodyAddressMax = 120;

export const locationsControllerCreateBodyNotesMax = 500;



export const LocationsControllerCreateBody = zod.object({
  "name": zod.string().min(locationsControllerCreateBodyNameMin).max(locationsControllerCreateBodyNameMax),
  "category": zod.enum(['office', 'store', 'landmark']),
  "coordinates": zod.object({
  "lon": zod.number().min(locationsControllerCreateBodyCoordinatesLonMin).max(locationsControllerCreateBodyCoordinatesLonMax),
  "lat": zod.number().min(locationsControllerCreateBodyCoordinatesLatMin).max(locationsControllerCreateBodyCoordinatesLatMax)
}),
  "address": zod.string().max(locationsControllerCreateBodyAddressMax).optional(),
  "notes": zod.string().max(locationsControllerCreateBodyNotesMax).optional()
})

export const locationsControllerCreateResponseNameMin = 2;
export const locationsControllerCreateResponseNameMax = 60;

export const locationsControllerCreateResponseCoordinatesLonMin = -180;
export const locationsControllerCreateResponseCoordinatesLonMax = 180;

export const locationsControllerCreateResponseCoordinatesLatMin = -90;
export const locationsControllerCreateResponseCoordinatesLatMax = 90;

export const locationsControllerCreateResponseAddressMax = 120;

export const locationsControllerCreateResponseNotesMax = 500;

export const locationsControllerCreateResponseCreatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$');
export const locationsControllerCreateResponseUpdatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$');


export const LocationsControllerCreateResponse = zod.object({
  "id": zod.string(),
  "name": zod.string().min(locationsControllerCreateResponseNameMin).max(locationsControllerCreateResponseNameMax),
  "category": zod.enum(['office', 'store', 'landmark']),
  "coordinates": zod.object({
  "lon": zod.number().min(locationsControllerCreateResponseCoordinatesLonMin).max(locationsControllerCreateResponseCoordinatesLonMax),
  "lat": zod.number().min(locationsControllerCreateResponseCoordinatesLatMin).max(locationsControllerCreateResponseCoordinatesLatMax)
}),
  "address": zod.string().max(locationsControllerCreateResponseAddressMax).optional(),
  "notes": zod.string().max(locationsControllerCreateResponseNotesMax).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).regex(locationsControllerCreateResponseCreatedAtRegExp),
  "updatedAt": zod.iso.datetime({"offset":true}).regex(locationsControllerCreateResponseUpdatedAtRegExp)
})

export const locationsControllerFindAllQuerySkipMin = 0;

export const locationsControllerFindAllQueryLimitMin = 0;



export const LocationsControllerFindAllQueryParams = zod.object({
  "skip": zod.number().min(locationsControllerFindAllQuerySkipMin).optional(),
  "limit": zod.number().min(locationsControllerFindAllQueryLimitMin).optional(),
  "category": zod.enum(['office', 'store', 'landmark']).optional()
})

export const locationsControllerFindAllResponseNameMin = 2;
export const locationsControllerFindAllResponseNameMax = 60;

export const locationsControllerFindAllResponseCoordinatesLonMin = -180;
export const locationsControllerFindAllResponseCoordinatesLonMax = 180;

export const locationsControllerFindAllResponseCoordinatesLatMin = -90;
export const locationsControllerFindAllResponseCoordinatesLatMax = 90;

export const locationsControllerFindAllResponseAddressMax = 120;

export const locationsControllerFindAllResponseNotesMax = 500;

export const locationsControllerFindAllResponseCreatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$');
export const locationsControllerFindAllResponseUpdatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$');


export const LocationsControllerFindAllResponseItem = zod.object({
  "id": zod.string(),
  "name": zod.string().min(locationsControllerFindAllResponseNameMin).max(locationsControllerFindAllResponseNameMax),
  "category": zod.enum(['office', 'store', 'landmark']),
  "coordinates": zod.object({
  "lon": zod.number().min(locationsControllerFindAllResponseCoordinatesLonMin).max(locationsControllerFindAllResponseCoordinatesLonMax),
  "lat": zod.number().min(locationsControllerFindAllResponseCoordinatesLatMin).max(locationsControllerFindAllResponseCoordinatesLatMax)
}),
  "address": zod.string().max(locationsControllerFindAllResponseAddressMax).optional(),
  "notes": zod.string().max(locationsControllerFindAllResponseNotesMax).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).regex(locationsControllerFindAllResponseCreatedAtRegExp),
  "updatedAt": zod.iso.datetime({"offset":true}).regex(locationsControllerFindAllResponseUpdatedAtRegExp)
})
export const LocationsControllerFindAllResponse = zod.array(LocationsControllerFindAllResponseItem)

export const LocationsControllerUpdateParams = zod.object({
  "id": zod.string()
})

export const locationsControllerUpdateBodyNameMin = 2;
export const locationsControllerUpdateBodyNameMax = 60;

export const locationsControllerUpdateBodyCoordinatesLonMin = -180;
export const locationsControllerUpdateBodyCoordinatesLonMax = 180;

export const locationsControllerUpdateBodyCoordinatesLatMin = -90;
export const locationsControllerUpdateBodyCoordinatesLatMax = 90;

export const locationsControllerUpdateBodyAddressMax = 120;

export const locationsControllerUpdateBodyNotesMax = 500;



export const LocationsControllerUpdateBody = zod.object({
  "name": zod.string().min(locationsControllerUpdateBodyNameMin).max(locationsControllerUpdateBodyNameMax).optional(),
  "category": zod.enum(['office', 'store', 'landmark']).optional(),
  "coordinates": zod.object({
  "lon": zod.number().min(locationsControllerUpdateBodyCoordinatesLonMin).max(locationsControllerUpdateBodyCoordinatesLonMax),
  "lat": zod.number().min(locationsControllerUpdateBodyCoordinatesLatMin).max(locationsControllerUpdateBodyCoordinatesLatMax)
}).optional(),
  "address": zod.string().max(locationsControllerUpdateBodyAddressMax).optional(),
  "notes": zod.string().max(locationsControllerUpdateBodyNotesMax).optional()
})

export const locationsControllerUpdateResponseNameMin = 2;
export const locationsControllerUpdateResponseNameMax = 60;

export const locationsControllerUpdateResponseCoordinatesLonMin = -180;
export const locationsControllerUpdateResponseCoordinatesLonMax = 180;

export const locationsControllerUpdateResponseCoordinatesLatMin = -90;
export const locationsControllerUpdateResponseCoordinatesLatMax = 90;

export const locationsControllerUpdateResponseAddressMax = 120;

export const locationsControllerUpdateResponseNotesMax = 500;

export const locationsControllerUpdateResponseCreatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$');
export const locationsControllerUpdateResponseUpdatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$');


export const LocationsControllerUpdateResponse = zod.object({
  "id": zod.string(),
  "name": zod.string().min(locationsControllerUpdateResponseNameMin).max(locationsControllerUpdateResponseNameMax),
  "category": zod.enum(['office', 'store', 'landmark']),
  "coordinates": zod.object({
  "lon": zod.number().min(locationsControllerUpdateResponseCoordinatesLonMin).max(locationsControllerUpdateResponseCoordinatesLonMax),
  "lat": zod.number().min(locationsControllerUpdateResponseCoordinatesLatMin).max(locationsControllerUpdateResponseCoordinatesLatMax)
}),
  "address": zod.string().max(locationsControllerUpdateResponseAddressMax).optional(),
  "notes": zod.string().max(locationsControllerUpdateResponseNotesMax).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).regex(locationsControllerUpdateResponseCreatedAtRegExp),
  "updatedAt": zod.iso.datetime({"offset":true}).regex(locationsControllerUpdateResponseUpdatedAtRegExp)
})

export const LocationsControllerRemoveParams = zod.object({
  "id": zod.string()
})

export const locationsControllerRemoveResponseNameMin = 2;
export const locationsControllerRemoveResponseNameMax = 60;

export const locationsControllerRemoveResponseCoordinatesLonMin = -180;
export const locationsControllerRemoveResponseCoordinatesLonMax = 180;

export const locationsControllerRemoveResponseCoordinatesLatMin = -90;
export const locationsControllerRemoveResponseCoordinatesLatMax = 90;

export const locationsControllerRemoveResponseAddressMax = 120;

export const locationsControllerRemoveResponseNotesMax = 500;

export const locationsControllerRemoveResponseCreatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$');
export const locationsControllerRemoveResponseUpdatedAtRegExp = new RegExp('^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$');


export const LocationsControllerRemoveResponse = zod.object({
  "id": zod.string(),
  "name": zod.string().min(locationsControllerRemoveResponseNameMin).max(locationsControllerRemoveResponseNameMax),
  "category": zod.enum(['office', 'store', 'landmark']),
  "coordinates": zod.object({
  "lon": zod.number().min(locationsControllerRemoveResponseCoordinatesLonMin).max(locationsControllerRemoveResponseCoordinatesLonMax),
  "lat": zod.number().min(locationsControllerRemoveResponseCoordinatesLatMin).max(locationsControllerRemoveResponseCoordinatesLatMax)
}),
  "address": zod.string().max(locationsControllerRemoveResponseAddressMax).optional(),
  "notes": zod.string().max(locationsControllerRemoveResponseNotesMax).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).regex(locationsControllerRemoveResponseCreatedAtRegExp),
  "updatedAt": zod.iso.datetime({"offset":true}).regex(locationsControllerRemoveResponseUpdatedAtRegExp)
})

