/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Locations
 * The locations API description
 * OpenAPI spec version: 1.0
 */
import type { CreateLocationDtoCategory } from './createLocationDtoCategory';
import type { CreateLocationDtoCoordinates } from './createLocationDtoCoordinates';

export interface CreateLocationDto {
  /**
     * @minLength 2
     * @maxLength 60
     */
  name: string;
  category: CreateLocationDtoCategory;
  coordinates: CreateLocationDtoCoordinates;
  /** @maxLength 120 */
  address?: string;
  /** @maxLength 500 */
  notes?: string;
}
