/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Locations
 * The locations API description
 * OpenAPI spec version: 1.0
 */

export * from './createLocationDto';
export * from './createLocationDtoCategory';
export * from './createLocationDtoCoordinates';
export * from './locationDto';
export * from './locationDtoCategory';
export * from './locationDtoCoordinates';
export * from './locationsControllerFindAllCategory';
export * from './locationsControllerFindAllParams';
export * from './updateLocationDto';
export * from './updateLocationDtoCategory';
export * from './updateLocationDtoCoordinates';
