/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Locations
 * The locations API description
 * OpenAPI spec version: 1.0
 */

export type LocationsControllerFindAllCategory = typeof LocationsControllerFindAllCategory[keyof typeof LocationsControllerFindAllCategory];


export const LocationsControllerFindAllCategory = {
  office: 'office',
  store: 'store',
  landmark: 'landmark',
} as const;
