/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Locations
 * The locations API description
 * OpenAPI spec version: 1.0
 */

export type LocationDtoCoordinates = {
  /**
     * @minimum -180
     * @maximum 180
     */
  lon: number;
  /**
     * @minimum -90
     * @maximum 90
     */
  lat: number;
};
