/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Locations
 * The locations API description
 * OpenAPI spec version: 1.0
 */

export type LocationDtoCategory = typeof LocationDtoCategory[keyof typeof LocationDtoCategory];


export const LocationDtoCategory = {
  office: 'office',
  store: 'store',
  landmark: 'landmark',
} as const;
