/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Locations
 * The locations API description
 * OpenAPI spec version: 1.0
 */
import type { LocationsControllerFindAllCategory } from './locationsControllerFindAllCategory';

export type LocationsControllerFindAllParams = {
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 0
 */
limit?: number;
category?: LocationsControllerFindAllCategory;
};
