/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Locations
 * The locations API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateLocationDtoCategory } from './updateLocationDtoCategory';
import type { UpdateLocationDtoCoordinates } from './updateLocationDtoCoordinates';

export interface UpdateLocationDto {
  /**
     * @minLength 2
     * @maxLength 60
     */
  name?: string;
  category?: UpdateLocationDtoCategory;
  coordinates?: UpdateLocationDtoCoordinates;
  /** @maxLength 120 */
  address?: string;
  /** @maxLength 500 */
  notes?: string;
}
