/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Locations
 * The locations API description
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


export const AppControllerGetHelloResponse = zod.unknown()

